name: Action Call Test
on: [workflow_dispatch]

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        uses: ps-actions-sandbox/rulasg-hello-world-docker-action@v1
        with:
          who-to-greet: '@octocat'
